version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: maestria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastify_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user_admin:secretpassword@db:5432/maestria_db?schema=public"
      PORT: 3001
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres_data: