version: '3.8'

services:
  # 1. Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: maestria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. API Backend
  backend:
    build: ./backend
    image: moisej25/practica_2_maestria-backend:latest
    container_name: backend_container
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:admin123@db:5432/maestria_db?schema=public"
    depends_on:
      - db

  # 3. Interfaz Web Frontend
  frontend:
    build: ./frontend
    image: moisej25/practica_2_maestria-frontend:latest
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: